### ISSUE TITLE
`fatal error: concurrent map writes` with multiple domains

### ISSUE THREAD

**Issue by sundbry** [mywordpress-io/certmagic-vault-storage#2]
Hi @kmott, here's another 🐛! I can reproduce this consistently - I added two domains to my Caddyfile which both do not have certs issued for them yet in the storage.

```
{"level":"info","ts":1700194998.3010652,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}                                      [312/1516]
{"level":"warn","ts":1700194998.302998,"msg":"Caddyfile input is not formatted; run 'caddy fmt --overwrite' to fix inconsistencies","adapter":"caddyfile","file":"/etc/caddy/Caddyfile","line":
2}
{"level":"info","ts":1700194998.3036695,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//localhost:2019","//[::1]:2019","//127.0
.0.1:2019"]}
{"level":"info","ts":1700194998.303866,"logger":"http.auto_https","msg":"server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS","server_name"
:"srv0","https_port":443}
{"level":"info","ts":1700194998.3038795,"logger":"http.auto_https","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"srv0"}
{"level":"info","ts":1700194998.3039427,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc000513000"}
{"level":"info","ts":1700194998.3043375,"logger":"http","msg":"enabling HTTP/3 listener","addr":":443"}
{"level":"info","ts":1700194998.3043482,"logger":"tls","msg":"cleaning storage unit","description":"&{0xc000128fc0 {https://vault:8200 x     kv caddy true <nil> <nil> }}"}
{"level":"info","ts":1700194998.3044736,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
{"level":"info","ts":1700194998.304563,"logger":"http.log","msg":"server running","name":"remaining_auto_https_redirects","protocols":["h1","h2","h3"]}
{"level":"info","ts":1700194998.304569,"logger":"http","msg":"enabling automatic TLS certificate management","domains":["a.mydomain.com","b.mydomain.com","c.mydomain.com"]}
{"level":"info","ts":1700194998.3139699,"logger":"tls","msg":"finished cleaning storage units"}
{"level":"info","ts":1700194998.317739,"msg":"autosaved config (load with --resume flag)","file":"/root/.config/caddy/autosave.json"}
{"level":"info","ts":1700194998.317757,"msg":"serving initial configuration"}
fatal error: concurrent map writes
fatal error: concurrent map writes

goroutine 36 [running]:
net/textproto.MIMEHeader.Set(...)
        /usr/local/go/src/net/textproto/header.go:22
net/http.Header.Set(...)
        /usr/local/go/src/net/http/header.go:40
gopkg.in/resty%2ev1.(*Client).SetHeader(...)
        /go/pkg/mod/gopkg.in/resty.v1@v1.12.0/client.go:144
github.com/mywordpress-io/certmagic-vault-storage/internal/client.(*Client).SetToken(0xc000308960, {0xc0000a5500, 0x5f})
        /go/pkg/mod/github.com/mywordpress-io/certmagic-vault-storage@v0.0.0-20230515230828-016c6bfcfe4d/internal/client/main.go:33 +0x9e
github.com/mywordpress-io/certmagic-vault-storage.(*Storage).Delete(0xc000128fc0, {0x0?, 0x1007a3858?}, {0xc0006b60c0, 0x1b})
        /go/pkg/mod/github.com/mywordpress-io/certmagic-vault-storage@v0.0.0-20230515230828-016c6bfcfe4d/main.go:192 +0x2e5
github.com/caddyserver/certmagic.(*Config).checkStorage.func1()
        /go/pkg/mod/github.com/caddyserver/certmagic@v0.19.2/config.go:1074 +0x5e
github.com/caddyserver/certmagic.(*Config).checkStorage(0xc0003f4000, {0x1ec3ca8, 0xc0005181e0})
        /go/pkg/mod/github.com/caddyserver/certmagic@v0.19.2/config.go:1092 +0x262
github.com/caddyserver/certmagic.(*Config).obtainCert(0xc0003f4000, {0x1ec3ca8, 0xc0005181e0}, {0xc00030ca40, 0x10}, 0x0)
        /go/pkg/mod/github.com/caddyserver/certmagic@v0.19.2/config.go:494 +0x165
github.com/caddyserver/certmagic.(*Config).ObtainCertAsync(...)
        /go/pkg/mod/github.com/caddyserver/certmagic@v0.19.2/config.go:479
github.com/caddyserver/certmagic.(*Config).manageOne.func1()
        /go/pkg/mod/github.com/caddyserver/certmagic@v0.19.2/config.go:398 +0x73
github.com/caddyserver/certmagic.(*jobManager).worker(0x2b4f480)
        /go/pkg/mod/github.com/caddyserver/certmagic@v0.19.2/async.go:73 +0x10f
created by github.com/caddyserver/certmagic.(*jobManager).Submit in goroutine 1
        /go/pkg/mod/github.com/caddyserver/certmagic@v0.19.2/async.go:50 +0x279
```

Representative Caddyfile:

```
{
  storage vault "https://vault:8200" {
    token "xyz"
    secrets_path "kv"
    path_prefix "caddy"
  }
}
a.mydomain.com, b.mydomain.com, c.mydomain.com {
  handle /livez {
    header Content-Type text/plain
    respond "OK" 200
  }
}
```

It appears that the fundamental issue is that the certmagic-vault-storage client (internal/client/main.go) is a singleton in the plugin, which can be invoked in parallel by the caddy server calling it. When this happens there are concurrent users of the Client and it's internal c.resty instance, and these parallel calls can conflict with eachother, causing this panic.

It's probably a good thing it panicked here too, since I suppose with a shared client in use if it did not, it could accidentally read or write the wrong TLS certificate for the domain!

**Comment by kmott** [comment]
Another good catch! I think I can avoid this by doing `SetHeader()` on the `R()`, rather than the global `resty` client.

**Comment by sundbry** [comment]
Hi @kmott, please take a look at #3 where I did something similar by eliminating some mutability. I verified the patch resolved the issue in my deployment.

**Comment by kmott** [comment]
@sundbry I checked the PR, and am happy to incorporate it once the questions are addressed.

**Comment by sundbry** [comment]
Hi @kmott, I don't think you submitted the comments/review -they are not visible to me!

**Comment by kmott** [comment]
@sundbry sorry, you were right (GitHub confuses me sometimes).  They should be visible now.
